name: "Foodie CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
        mongodb-version: [ '6.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up Python 3.10
        uses: actions/checkout@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Set up cache
        uses: actions/cache@v3
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Lint with black
        run: |
          poetry add black
          poetry run black --check .

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pytest -s --cov=app --cov-fail-under=50 --cov-config=.coveragerc --cov-report=term-missing --cov-report=xml tests/